project:
  type: website
  output-dir: docs
  
execute: 
  freeze: true

website:
  title: "Aradhya Rathi."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Portfolio.qmd
      
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/aradhyarathi/
        
  page-footer: 
    center: |
      @ 2023 [Aradhya Rathi]
      Copyright License 
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

